services:
  mongo:
    image: mongo:6.0
    container_name: fastapi_interview_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017"
    volumes:
      - fastapi_mongo_data:/data/db

  api:
    build:
      context: .
      target: build-${TODO__NODE_ENV}
    container_name: fastapi_interview_api
    env_file: .env
    environment:
      MONGO_DETAILS: mongodb://mongo:27017/test
    command: debugpy --listen 0.0.0.0:8101 -m uvicorn --reload --host 0.0.0.0 --port 8000 api.main:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8101:8101"
    depends_on:
      - mongo

volumes:
  fastapi_mongo_data:
