services:

  postgresql:
    image: postgres:latest
    container_name: fastapi_todo_db
    environment: &postgres_creds
      PGDATA: /var/lib/postgresql/data/fastapi_pg_data
      POSTGRES_DB: ${TODO__DB__DB}
      POSTGRES_USER: ${TODO__DB__USER}
      POSTGRES_PASSWORD: ${TODO__DB__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - fastapi_pg_data:/var/lib/postgresql/data/fastapi_pg_data

  api:
    build:
      context: .
      target: build-${TODO__NODE_ENV}
    container_name: fastapi_todo_api
    env_file: .env
    environment:
      <<: 
        - *postgres_creds
      POSTGRES_HOST: postgresql
    command: gunicorn -c gunicorn.dev.conf.py api.main:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

volumes:
  fastapi_pg_data:

networks:
  default:
    name: fastapi_todo_pet
    external: true