"""Create book, publisher, book_publisher_map tables.

Revision ID: 228884065bfe
Revises: 
Create Date: 2025-09-25 20:39:50.703079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228884065bfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('DRAMA', 'SCIENCE', 'FICTION', 'FANTASY', 'HORROR', 'ADVENTURE', name='bookstype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book')),
    sa.UniqueConstraint('title', name=op.f('uq_book_title'))
    )
    op.create_table('publisher',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'DRAFT', 'NEED_TO_APPROVE', name='publisherstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publisher')),
    sa.UniqueConstraint('name', name=op.f('uq_publisher_name'))
    )
    op.create_table('book_publisher_map',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_publisher_map_book_id_book'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name=op.f('fk_book_publisher_map_publisher_id_publisher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'publisher_id', name=op.f('pk_book_publisher_map'))
    )
    op.create_table('publisher_status_history',
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('OPEN', 'CLOSED', 'DRAFT', 'NEED_TO_APPROVE', name='publisherstatus'), nullable=False),
    sa.Column('current_status', sa.Enum('OPEN', 'CLOSED', 'DRAFT', 'NEED_TO_APPROVE', name='publisherstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], name=op.f('fk_publisher_status_history_publisher_id_publisher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publisher_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher_status_history')
    op.drop_table('book_publisher_map')
    op.drop_table('publisher')
    op.drop_table('book')
    # ### end Alembic commands ###
