"""Added tasks tables and comment table.

Revision ID: 248aec99e661
Revises: 39717c96f7ff
Create Date: 2025-07-06 17:10:16.749280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248aec99e661'
down_revision: Union[str, Sequence[str], None] = '39717c96f7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_core',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'FEATURE', 'IMPROVEMENT', name='tasktype'), nullable=False),
    sa.Column('priority', sa.Enum('BLOCKER', 'CRITICAL', 'MAJOR', 'MINOR', 'TRIVIAL', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user_core.id'], name=op.f('fk_task_core_assigned_user_id_user_core'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task_core.id'], name=op.f('fk_task_core_parent_task_id_task_core'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_core'))
    )
    op.create_table('comment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], name=op.f('fk_comment_parent_comment_id_comment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_core.id'], name=op.f('fk_comment_task_id_task_core'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_core.id'], name=op.f('fk_comment_user_id_user_core')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('task_assignees_history',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=True),
    sa.Column('current_assignee_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user_core.id'], name=op.f('fk_task_assignees_history_changed_by_user_id_user_core')),
    sa.ForeignKeyConstraint(['current_assignee_id'], ['user_core.id'], name=op.f('fk_task_assignees_history_current_assignee_id_user_core')),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['user_core.id'], name=op.f('fk_task_assignees_history_previous_assignee_id_user_core')),
    sa.ForeignKeyConstraint(['task_id'], ['task_core.id'], name=op.f('fk_task_assignees_history_task_id_task_core'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_assignees_history'))
    )
    op.create_table('task_attachment_map',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], name=op.f('fk_task_attachment_map_attachment_id_attachment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_core.id'], name=op.f('fk_task_attachment_map_task_id_task_core'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'attachment_id', name=op.f('pk_task_attachment_map'))
    )
    op.create_table('task_detail',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_core.id'], name=op.f('fk_task_detail_task_id_task_core'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_task_detail'))
    )
    op.create_table('task_status_history',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=True),
    sa.Column('current_status', sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['user_core.id'], name=op.f('fk_task_status_history_changed_by_user_id_user_core')),
    sa.ForeignKeyConstraint(['task_id'], ['task_core.id'], name=op.f('fk_task_status_history_task_id_task_core'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_status_history'))
    )
    op.drop_constraint(op.f('fk_user_detail_user_id_user_core'), 'user_detail', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_detail_user_id_user_core'), 'user_detail', 'user_core', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_detail_user_id_user_core'), 'user_detail', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_detail_user_id_user_core'), 'user_detail', 'user_core', ['user_id'], ['id'])
    op.drop_table('task_status_history')
    op.drop_table('task_detail')
    op.drop_table('task_attachment_map')
    op.drop_table('task_assignees_history')
    op.drop_table('comment')
    op.drop_table('task_core')
    # ### end Alembic commands ###
