"""Create tables: attachment, user_core, user_detail

Revision ID: 39717c96f7ff
Revises: 
Create Date: 2025-07-06 11:34:42.733244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39717c96f7ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('upload_status', sa.Enum('PENDING', 'UPLOADED', 'ERROR', name='attachmentuploadstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('link', name=op.f('uq_attachment_link'))
    )
    op.create_table('user_core',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'INACTIVE', 'ACTIVE', name='userstatus'), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['attachment.id'], name=op.f('fk_user_core_avatar_id_attachment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_core')),
    sa.UniqueConstraint('email', name=op.f('uq_user_core_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_core_username'))
    )
    op.create_table('user_detail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=50), nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'CHINESE', 'JAPANESE', 'KOREAN', 'RUSSIAN', 'ARABIC', 'PORTUGUESE', 'HINDI', 'BENGALI', 'ITALIAN', 'TURKISH', 'DUTCH', 'POLISH', 'UKRAINIAN', name='language'), nullable=False),
    sa.Column('timezone', sa.Enum('UTC', 'US_EASTERN', 'US_CENTRAL', 'US_MOUNTAIN', 'US_PACIFIC', 'EUROPE_LONDON', 'EUROPE_BERLIN', 'EUROPE_PARIS', 'ASIA_TOKYO', 'ASIA_SHANGHAI', 'ASIA_KOLKATA', 'AUSTRALIA_SYDNEY', 'SOUTH_AMERICA_SAO_PAULO', 'AFRICA_JOHANNESBURG', 'PACIFIC_AUCKLAND', name='timezone'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_core.id'], name=op.f('fk_user_detail_user_id_user_core')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_detail'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_detail')
    op.drop_table('user_core')
    op.drop_table('attachment')
    # ### end Alembic commands ###
