"""Update password size.

Revision ID: 67a06f106d80
Revises: 909feea74595
Create Date: 2025-07-06 22:34:08.309140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a06f106d80'
down_revision: Union[str, Sequence[str], None] = '909feea74595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'parent_comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_core', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_core', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('comment', 'parent_comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
